# fly.toml app configuration file generated for birthday-reminder-mrsun on 2023-12-29T16:47:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "birthday-reminder-mrsun"
primary_region = "mia"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
